import type { Metadata } from "next";

import "./globals.css";


import { Nunito } from 'next/font/google';




const nunito = Nunito({ 
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Boardroom Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
     className={nunito.className}
      >
        {children}
      </body>
    </html>
  );
}
